CREATE DATABASE IF NOT EXISTS product_catalog
  CHARACTER SET utf8mb4
  COLLATE utf8mb4_unicode_ci;

USE product_catalog;

CREATE TABLE IF NOT EXISTS products (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  name VARCHAR(80) NOT NULL,
  sector VARCHAR(20) NOT NULL,
  cost DECIMAL(10, 2) NOT NULL DEFAULT 0.00,
  sale_price DECIMAL(10, 2) NOT NULL DEFAULT 0.00,
  stock INT UNSIGNED NOT NULL DEFAULT 0,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  CONSTRAINT products_cost_nonnegative CHECK (cost >= 0),
  CONSTRAINT products_sale_price_nonnegative CHECK (sale_price >= 0)
) ENGINE=InnoDB;
